"""add email and password to mentor table

Revision ID: 09f96105a1af
Revises: c073b793b63c
Create Date: 2026-01-13 15:33:11.802686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f96105a1af'
down_revision = 'c073b793b63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
